config/routes.rb
Trypostgresql::Application.routes.draw do
  resources :dudes

  resources :aliens

end

app/models/alien.rb
# == Schema Information
#
# Table name: aliens
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Alien < ActiveRecord::Base
  attr_accessible :name, :photo, :audiofile

  mount_uploader :audiofile, AudioloadUploader
end

app/models/dude.rb
# == Schema Information
#
# Table name: dudes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Dude < ActiveRecord::Base
  attr_accessible :name, :photo, :audiofile

  mount_uploader :audiofile, AudioloadUploader
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  audiofile  :string(255)
#

class Song < ActiveRecord::Base
  attr_accessible :name, :price, :audiofile

  mount_uploader :audiofile, AudioloadUploader
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  # GET /aliens
  # GET /aliens.json
  def index
    @aliens = Alien.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aliens }
    end
  end

  # GET /aliens/1
  # GET /aliens/1.json
  def show
    @alien = Alien.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alien }
    end
  end

  # GET /aliens/new
  # GET /aliens/new.json
  def new
    @alien = Alien.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alien }
    end
  end

  # GET /aliens/1/edit
  def edit
    @alien = Alien.find(params[:id])
  end

  # POST /aliens
  # POST /aliens.json
  def create
    @alien = Alien.new(params[:alien])

    respond_to do |format|
      if @alien.save
        format.html { redirect_to @alien, notice: 'Alien was successfully created.' }
        format.json { render json: @alien, status: :created, location: @alien }
      else
        format.html { render action: "new" }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aliens/1
  # PUT /aliens/1.json
  def update
    @alien = Alien.find(params[:id])

    respond_to do |format|
      if @alien.update_attributes(params[:alien])
        format.html { redirect_to @alien, notice: 'Alien was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliens/1
  # DELETE /aliens/1.json
  def destroy
    @alien = Alien.find(params[:id])
    @alien.destroy

    respond_to do |format|
      format.html { redirect_to aliens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dudes_controller.rb
class DudesController < ApplicationController
  # GET /dudes
  # GET /dudes.json
  def index
    @dudes = Dude.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dudes }
    end
  end

  # GET /dudes/1
  # GET /dudes/1.json
  def show
    @dude = Dude.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dude }
    end
  end

  # GET /dudes/new
  # GET /dudes/new.json
  def new
    @dude = Dude.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dude }
    end
  end

  # GET /dudes/1/edit
  def edit
    @dude = Dude.find(params[:id])
  end

  # POST /dudes
  # POST /dudes.json
  def create
    @dude = Dude.new(params[:dude])

    respond_to do |format|
      if @dude.save
        format.html { redirect_to @dude, notice: 'Dude was successfully created.' }
        format.json { render json: @dude, status: :created, location: @dude }
      else
        format.html { render action: "new" }
        format.json { render json: @dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dudes/1
  # PUT /dudes/1.json
  def update
    @dude = Dude.find(params[:id])

    respond_to do |format|
      if @dude.update_attributes(params[:dude])
        format.html { redirect_to @dude, notice: 'Dude was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dudes/1
  # DELETE /dudes/1.json
  def destroy
    @dude = Dude.find(params[:id])
    @dude.destroy

    respond_to do |format|
      format.html { redirect_to dudes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dudes_helper.rb
module DudesHelper
end

app/views/aliens/_form.html.erb
<%= form_for(@alien) do |f| %>
  <% if @alien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alien.errors.count, "error") %> prohibited this alien from being saved:</h2>

      <ul>
      <% @alien.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :audiofile %><br />
    <%= f.file_field :audiofile %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aliens/edit.html.erb
<h1>Editing alien</h1>

<%= render 'form' %>

<%= link_to 'Show', @alien %> |
<%= link_to 'Back', aliens_path %>

app/views/aliens/index.html.erb
<h1>Listing aliens</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aliens.each do |alien| %>
  <tr>
    <td><%= alien.name %></td>
    <td><%= alien.photo %></td>
    <td><%= link_to 'Show', alien %></td>
    <td><%= link_to 'Edit', edit_alien_path(alien) %></td>
    <td><%= link_to 'Destroy', alien, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alien', new_alien_path %>

app/views/aliens/new.html.erb
<h1>New alien</h1>

<%= render 'form' %>

<%= link_to 'Back', aliens_path %>

app/views/aliens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @alien.name %>
</p>

<p>
  <b>Photo:</b>
  <%= @alien.photo %>
</p>


<%= link_to 'Edit', edit_alien_path(@alien) %> |
<%= link_to 'Back', aliens_path %>

app/views/dudes/_form.html.erb
<%= form_for(@dude) do |f| %>
  <% if @dude.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dude.errors.count, "error") %> prohibited this dude from being saved:</h2>

      <ul>
      <% @dude.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :audiofile %><br />
    <%= f.file_field :audiofile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dudes/edit.html.erb
<h1>Editing dude</h1>

<%= render 'form' %>

<%= link_to 'Show', @dude %> |
<%= link_to 'Back', dudes_path %>

app/views/dudes/index.html.erb
<h1>Listing dudes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dudes.each do |dude| %>
  <tr>
    <td><%= dude.name %></td>
    <td><%= dude.photo %></td>
    <td><%= link_to 'Show', dude %></td>
    <td><%= link_to 'Edit', edit_dude_path(dude) %></td>
    <td><%= link_to 'Destroy', dude, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dude', new_dude_path %>

app/views/dudes/new.html.erb
<h1>New dude</h1>

<%= render 'form' %>

<%= link_to 'Back', dudes_path %>

app/views/dudes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dude.name %>
</p>

<p>
  <b>Photo:</b>
  <%= @dude.photo %>
</p>


<%= link_to 'Edit', edit_dude_path(@dude) %> |
<%= link_to 'Back', dudes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trypostgresql</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>